### ISSUE TITLE
Validate on position on work form (talent)

### ISSUE THREAD

**Issue by faris-bara** [trikarai/inovasi-vue-cli3#20]
Working Experiences > Work Experiences

**Comment by trisutrisno-id** [comment]
fix : https://github.com/trikarai/inovasi-vue-cli3/commit/e89c59f49a72d37927ed0fdf840c757d0dcc0f0f

fix2 : https://github.com/trikarai/inovasi-vue-cli3/commit/478392cdba9e5f01165eccac1fc64afb0ab1fc93
