### ISSUE TITLE
Cannot cancel program participation (talent)

### ISSUE THREAD

**Issue by faris-bara** [trikarai/inovasi-vue-cli3#24]

**Comment by trisutrisno-id** [comment]
fix : https://github.com/trikarai/inovasi-vue-cli3/commit/ad12d8690cf00409634b76ccef3d3e76d977bae2

**Comment by trisutrisno-id** [comment]
fix 2 : https://github.com/trikarai/inovasi-vue-cli3/commit/47a1684ac12dba1dea3b51027c1d7908f5a4b8f7
